// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_dYL6mDyPHLZ599WxIO6r6WI-XU65Oyk',
    appId: '1:813084970288:web:624ea74393c812874b0cf5',
    messagingSenderId: '813084970288',
    projectId: 'eldcare-b043d',
    authDomain: 'eldcare-b043d.firebaseapp.com',
    databaseURL: 'https://eldcare-b043d-default-rtdb.firebaseio.com',
    storageBucket: 'eldcare-b043d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGILkoXAhH4XytMbxwtGSttf0DE3VB6hM',
    appId: '1:813084970288:android:e8a75585aad1415b4b0cf5',
    messagingSenderId: '813084970288',
    projectId: 'eldcare-b043d',
    databaseURL: 'https://eldcare-b043d-default-rtdb.firebaseio.com',
    storageBucket: 'eldcare-b043d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqe5FNQGhN78Q0OnPNN_QgEoWad9nhd4',
    appId: '1:813084970288:ios:98ec5c78faea08574b0cf5',
    messagingSenderId: '813084970288',
    projectId: 'eldcare-b043d',
    databaseURL: 'https://eldcare-b043d-default-rtdb.firebaseio.com',
    storageBucket: 'eldcare-b043d.firebasestorage.app',
    iosBundleId: 'com.example.eldcareCaretakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqe5FNQGhN78Q0OnPNN_QgEoWad9nhd4',
    appId: '1:813084970288:ios:98ec5c78faea08574b0cf5',
    messagingSenderId: '813084970288',
    projectId: 'eldcare-b043d',
    databaseURL: 'https://eldcare-b043d-default-rtdb.firebaseio.com',
    storageBucket: 'eldcare-b043d.firebasestorage.app',
    iosBundleId: 'com.example.eldcareCaretakerApp',
  );

}